version: "3.7"

services:
  postgres:
    image: postgres:11.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  ad-service:
    image: node:12
    ports:
      - 3000:3000
    working_dir: /usr/local/app
    volumes:
      - ./:/usr/local/app
      - /usr/local/app/node_modules/
    env_file:
      - ./.env
    command: bash -c "npm install && npm run start:dev"
    depends_on:
      - postgres
